### ISSUE TITLE
cmake: add more modules, finish porting make build system

### ISSUE THREAD

**Issue by jgoppert** [jgoppert/Firmware#19]
@mcharleb, @LorenzMeier, @modevico, @david5, @TSC21 This can be a new thread for us to discuss what we need to do to finish up the cmake branch. I also renamed this branch cmake and deleted all of my other cmake attempts as I think this is very close now.
# TODO:
## Common
- Add more modules.
## Nuttx
- ROMFS generation
- builtin_commands.c generation
- add upload targets
- add debug targets
- add more board configs to config list/ makefile
## Qurt
- Add unit testing
- ?
## Posix
- Add unit testing
- ?

**Comment by jgoppert** [comment]
I've added the accelsim, filter, simulator, and conversion modules. It builds with posix and nuttx still. Don't have a build environment for qurt set up.

Can anyone volunteer to take a subset of the modules. I'm going to focus on gettnig the rest of the posix sitl apps running, including the other sim drivers.

**Comment by jgoppert** [comment]
I don't want to submit another WIP pull request, so I just pull requested to myself, since it is helpful to see commits as they happen. Please post comments here:  #20

**Comment by mcharleb** [comment]
I had started working on those this morning (accelsim...), just didn't get to push them out yet.

**Comment by jgoppert** [comment]
@mcharleb Yeah, assume that is going to happen a lot unless we assign groups to people to convert, or just commit regularly.

**Comment by mcharleb** [comment]
@jgoppert One nice feature to have would be that the only git submodules that are init'ed are only those required for your target build. For instance, if you don'y use uavcan, you should not need to download it, similarly for nuttx and eventually dspal (for qurt). If others have already been init'ed then no need to deinit them (but that would also be possible).

**Comment by jgoppert** [comment]
@mcharleb Agreed. I have the git repos as targets, so if the target isn't linked to the ALL target somehow, it never gets called. So that has already been working for me.
